### ISSUE TITLE
Gitlab account credentials

### ISSUE THREAD

**Issue by keenanlang** [keenanlang/mkioc#5]
When using the script under a user account that hasn't set up their ssh credentials with gitlab, the script will error out with an unhelpful message. This is especially egregious when using the flags to not push to gitlab, so it is confusing for the user why gitlab credentials are needed.

Possible fixes:

* Make gitlab working copies of xxx public instead of internal  
* Make the script copy from /APSshare to get its base version of xxx  
* Add a flag to specify a user to use with gitlab

**Comment by kmpeters** [comment]
I like making gitlab working copies of xxx public instead of internal, since it would make the scripts usable by those who don't have access to APSshare.

**Comment by keenanlang** [comment]
Looks like in order to make xxx public visible, the entire group of synApps_X_Y_Working has to be made visible. I don't think this should be an issue, but may result in more email spam if we're going to be getting monthly emails for everything like Pete was talking about.

**Comment by kmpeters** [comment]
There isn't a lot of value in making all the modules we deploy publicly available.

I think copying from /APSshare would be ok if there was an option to pull a specific tag from **github**.  That would make it useful even if /APSshare wasn't available.

**Comment by keenanlang** [comment]
I ended up making it so that the gitlab option determines whether the IOC is copied from /APSshare. If you use -g, the script will fetch from gitlab, if you use -n, the script will copy from /APSshare.
